name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: HACS Validation
        uses: hacs/action@dcb30e72781db3f207d5236b861172774ab0b485 # main
        with:
          category: integration
